### PR TITLE
Measure test coverage

### LINKED ISSUE #10: Measure test coverage
Use simplecov to measure test coverage.

### PR DESCRIPTION
**Pull request by jdrago999**
Resolves #10

### CODE REVIEW

**Comment by jdrago999** [comment]
This PR also resolves #8 and #6 because I branched off of the PRs for those issues.

**Comment by avakarev** [comment]
@jdrago999 Thanks a lot for you MR! I already have some related changes in my private branch for a while. Including `minitest -> respec` transition and some refactorings: extracting faraday dependency as mailbox connection, etc. So, let me please rebase and merge, and then we can merge your MR into latest master. I will update you soon.

**Comment by avakarev** [comment]
@jdrago999 Done. Would you like to rebase you branch on MR or makes more sense to make another PR?

**Comment by jdrago999** [comment]
I will rebase and create a new PR tonight. Thank you!

**Comment by ArthurWD** [comment]
Any chance you'll pick this up again? Would be great!

**Comment by avakarev** [comment]
@ArthurWD, it's done in #17 and #18. I will release new gem version in ~10 hours.

**Pull request closed without merging**
